
jobs:
  - script: >
      job('seed_job') {
        scm {
          git {
              remote {
                  url('https://github.com/shurikg/sce_ci_environment.git')
              }
              branch('main')
              extensions {
                wipeOutWorkspace()
              }
          }
        }
        steps {
            dsl {
                external('jenkins/jobs/*.groovy')
            }
        }
        triggers {
            scm('* * * * *')
        }
      }
