jenkins:
  systemMessage: |
    Welcome to SCE Jenkins server.
  numExecutors: 10
groovy:
  - script: >
      import com.cloudbees.hudson.plugins.folder.Folder;
      import jenkins.model.Jenkins;
      
      def numOfTeams = 22;
      println("Create Folder for teams [" + numOfTeams + "]");
      (1..numOfTeams).each { currentIndex ->
        def folderName = 'Team_' + currentIndex;
        if (Jenkins.instance.getItem(folderName) == null) {
          Jenkins.instance.createProject(Folder.class, folderName);
        };
      };
      def exampleFolderName = "Examples";
      if (Jenkins.instance.getItem(exampleFolderName) == null) {
          Jenkins.instance.createProject(Folder.class, exampleFolderName);
      };
jobs:
  - script: >
      pipelineJob('Examples/Maven-Example') {
          description('Java/Maven example job. Reference - https://github.com/jenkins-docs/simple-java-maven-app')
          definition {
              cpsScm {
                  scriptPath 'jenkins/Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkins-docs/simple-java-maven-app.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }
  - script: >
      pipelineJob('Examples/Python-Example') {
          description('Java/Maven example job. Reference - https://github.com/shurikg/simple-python-pyinstaller-app')
          definition {
              cpsScm {
                  scriptPath 'jenkins/Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/shurikg/simple-python-pyinstaller-app.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }

